from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

import numpy as np
import pandas as pd

from solar_agent.core.models import ForecastMetadata


class ForecastProvider(Protocol):
    def get_hourly(self, start: pd.Timestamp, hours: int) -> tuple[pd.DataFrame, ForecastMetadata]:
        """Return weather indexed by timezone-aware timestamps."""


class SyntheticForecastProvider:
    """Deterministic weather-shaped data for a reliable, explicitly labeled demo."""

    def get_hourly(self, start: pd.Timestamp, hours: int) -> tuple[pd.DataFrame, ForecastMetadata]:
        index = pd.date_range(start=start.floor("h"), periods=hours, freq="h")
        hour = index.hour.to_numpy()
        day = (index.normalize() - index[0].normalize()).days.to_numpy()

        daylight = np.maximum(0, np.sin(np.pi * (hour - 6) / 12))
        cloud_factor = np.clip(
            0.76
            + 0.18 * np.sin((hour + day * 3) * 0.65)
            - 0.16 * (day % 2),
            0.30,
            1.0,
        )
        ghi = 850 * daylight * cloud_factor
        temperature = 15 + 8 * daylight + 2 * np.sin(hour / 3)
        wind_speed = 1.8 + 1.2 * np.cos(hour / 4)

        frame = pd.DataFrame(
            {
                "ghi_wm2": ghi,
                "cloud_factor": cloud_factor,
                "temperature_c": temperature,
                "wind_speed_ms": np.maximum(wind_speed, 0.2),
            },
            index=index,
        )
        now = datetime.now(UTC)
        metadata = ForecastMetadata(
            provider="Synthetic weather provider",
            mode="simulation",
            initialized_at=now,
            generated_at=now,
            is_live=False,
            limitations=[
                "This forecast is synthetic and was not generated by Aurora.",
                "Replace it with a validated Foundry + ERA5 artifact before claiming "
                "Aurora output.",
            ],
        )
        return frame, metadata


class CachedAuroraForecastProvider:
    """Loads a validated location-level Aurora forecast exported from the Foundry pipeline."""

    REQUIRED_COLUMNS = {
        "timestamp",
        "ghi_wm2",
        "cloud_factor",
        "temperature_c",
        "wind_speed_ms",
    }

    def __init__(self, path: Path) -> None:
        self.path = path

    def get_hourly(self, start: pd.Timestamp, hours: int) -> tuple[pd.DataFrame, ForecastMetadata]:
        data = pd.read_parquet(self.path)
        missing = self.REQUIRED_COLUMNS.difference(data.columns)
        if missing:
            raise ValueError(f"Aurora artifact is missing columns: {sorted(missing)}")

        data["timestamp"] = pd.to_datetime(data["timestamp"], utc=True)
        data = data.set_index("timestamp").sort_index()
        subset = data.loc[data.index >= start.tz_convert("UTC")].head(hours)
        if len(subset) < hours:
            raise ValueError(f"Aurora artifact has {len(subset)} hours; {hours} are required")

        initialized_at = pd.Timestamp(
            data.attrs.get("initialized_at", subset.index[0])
        ).to_pydatetime()
        generated_at = pd.Timestamp(
            data.attrs.get("generated_at", subset.index[0])
        ).to_pydatetime()
        metadata = ForecastMetadata(
            provider="Microsoft Aurora 1.5 on Foundry",
            mode=str(data.attrs.get("mode", "cached-era5")),
            initialized_at=initialized_at,
            generated_at=generated_at,
            is_live=False,
            limitations=["ERA5/ERA5T initialization trails real time and must show its timestamp."],
        )
        return subset, metadata
